export const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";
export const VALIDATE_USER = "VALIDATE_USER";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_PENDING = "USER_LOGIN_PENDING";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const FETCH_DOCUMENTS = "FETCH_DOCUMENTS"