export const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";
export const VALIDATE_USER = "VALIDATE_USER";

export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGIN_PENDING = "USER_LOGIN_PENDING";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";